### ISSUE TITLE
Gun statistics such as aimcone can be changed by clients

### ISSUE THREAD

**Issue by Frosty11234** [ModularMods/ModularWarfare#41]
Me and a friend are testing the weapon spread mechanic, the server and my friend are both using the same content pack with the aim cone of the mosin nagant set to 0.

I am using the same pack except my aim cone is set to 2.4

Logically the server would change mine to match however its resulted in all my shots missing and his not. A video is below to show the issue

https://youtu.be/uV_snnR_0w8

I would have anticipated the "modified_pack_server_kick": true" to kick me for having a different pack, however it just does not do this. I had 0 permissions other than being whitelisted on the server

**Comment by Protoxy22** [comment]
Hello, thanks for reporting that.
It was a mistake from my side, I forgot to add a player kick if essential gun's stat are modified.
https://github.com/ModularMods/ModularWarfare/blob/2dffe34621dfba5e3b1150b8de6c128567b4d915/src/main/java/com/modularwarfare/common/network/PacketExpGunFire.java#L154
