### ISSUE TITLE
MaxStackSize and dropBulletCasing(false) doesn't work.

### ISSUE THREAD

**Issue by eslairdjv** [ModularMods/ModularWarfare#43]
Max Stack Size doesn't work. And dropBulletCasing(false) in guns folder doesn't work.
But dropBulletCasing(false) in mod_config.json worked.

**Comment by Cooper233** [comment]
If you check the code you'll find that, for ammo item they set the MaxStackSize to 4.
And that overide your config.

**Comment by eslairdjv** [comment]
> コードを確認すると、弾薬アイテムの MaxStackSize が 4 に設定されていることがわかります。これにより、構成 が上書きされます。

How to rewrite that code

**Comment by Cooper233** [comment]
com.modularwarfare.common.guns.ItemAmmo
in the constructor `public ItemAmmo(AmmoType type)`, you can see `this.setMaxStackSize(4);`
just delete it or rewrite it into `this.setMaxStackSize(type.maxStackSize);`
I don't know why the author doesn't fix it even now(beta 2.0). Maybe it's a feature or they just forget it?

**Comment by eslairdjv** [comment]
> コンストラクターのcom.modularwarfare.common.guns.ItemAmmo は、 削除するか、書き直すだけで`public ItemAmmo(AmmoType type)`わかります 。作者がなぜ今でも修正しないのかわかりません(ベータ 2.0)。多分それは機能ですか、それとも彼らはそれを忘れていますか？`this.setMaxStackSize(4);``this.setMaxStackSize(type.maxStackSize);`

ありがとうございます。
